### ISSUE TITLE
Code Cleanup required

### ISSUE THREAD

**Issue by nabeeljay** [nabeeljay/team0-dash#1]
Lots of redundant files and codes. Need cleanup.

**Comment by thePlebDev** [comment]
still up for grabs? I can clean up the code and files

**Comment by nabeeljay** [comment]
> still up for grabs? I can clean up the code and files 

Sure you can :)

**Comment by nabeeljay** [comment]
Closing as the issue is fixed now. Thanks for the help @thePlebDev
